/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{html,js}",
    "../components/**/*.{html,js,vue}",
    "./src/components/*.{html,js,vue}",
    "./src/views/*.{html,js,vue}",
    "./src/views/*.{html,js,vue}/",
    "./*.{html,js}",
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // pattern: [
    "text-white",
    "bg-blue-400",
    "p-5",
    "flex-col",
    "items-center",
    "text-xl",
    "pt-2",
    "-mb-11",
    "text-red-600",
    "body-font",
    "overflow-hidden",
    "container",
    "px-5",
    "py-24",
    "mx-auto",
    "lg:w-4/5",
    "flex",
    "flex-wrap",
    "lg:w-1/2",
    "w-full",
    "lg:h-auto",
    "h-64",
    "object-cover",
    "object-center",
    "rounded",
    // /^tracking-/,
    // /^mb-/,
    // /^font-/,
    // /^flex/,
    // /^leading-/,
    // /^items-/,
    // /^pb-/,
    // /^border-/,
    // /^mr-/,
    // /^relative/,
    // /^rounded/,
    // /^border/,
    // /^appearance-/,
    // /^focus:outline-/,
    // /^focus:ring-/,
    // /^focus:border-/,
    // /^pl-/,
    // /^pr-/,
    // /^absolute/,
    // /^right-/,
    // /^pr-/,
    // /^top-/,
    // /^pointer-/,
    // /^justify-/,
    // /^ml-/,
    // /^bg-/,
    // /^hover:bg-/,
    // ],
    // <= ここの部分
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
